# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'hts2v2artifactory'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    packagesDirectory: 'E:\Cache\NuGetPackages'